//! Fixed iRecovery worker for device-exact ramdisk provider packs.
//!
//! The worker executes only typed `-f <approved asset>` and `-c <approved
//! command>` instructions generated by `tg-ramdisk-pack`. Waits and checkpoints
//! must be acknowledged separately by the controller.

use std::collections::{BTreeMap, BTreeSet};
use std::fs::File;
use std::io::Read;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use tg_apple_observe::LockedDeviceIdentity;
use tg_contracts::{DeviceMode, Maturity, Permission};
use tg_gaster_provider::GasterFinalProof;
use tg_process::{run_supervised, ProcessPolicy, ProcessSpec, SupervisedOutcome};
use tg_ramdisk_pack::{
    validate_pack, AssetRole, BootCheckpoint, BootStep, FixedRecoveryCommand, RamdiskProviderPack,
};
use uuid::Uuid;

pub const RAMDISK_BOOT_VERSION: &str = "tgcheckm8.ramdisk-boot.v1";
pub const IRECOVERY_SOURCE_REPOSITORY: &str = "https://github.com/libimobiledevice/libirecovery";
pub const IRECOVERY_SOURCE_COMMIT: &str = "04d04f7cbaa4696504e91c1478ddd56160ed6776";
pub const IRECOVERY_LICENCE: &str = "LGPL-2.1-or-later";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct IRecoveryProviderManifest {
    pub schema_version: String,
    pub provider_id: String,
    pub source_repository: String,
    pub source_commit: String,
    pub licence: String,
    pub executable_sha256: Option<String>,
    pub maturity: Maturity,
    pub requested_permissions: BTreeSet<Permission>,
    pub proof_requirements: BTreeSet<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BootInstallation {
    pub irecovery_executable: PathBuf,
    pub working_directory: PathBuf,
    pub asset_root: PathBuf,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BootStartRequest<'a> {
    pub session_id: Uuid,
    pub pack: &'a RamdiskProviderPack,
    pub irecovery_manifest: &'a IRecoveryProviderManifest,
    pub gaster_proof: &'a GasterFinalProof,
    pub locked_identity: &'a LockedDeviceIdentity,
    pub installation: &'a BootInstallation,
    pub authorized_device_service: bool,
    pub explicit_operator_authorization: bool,
    pub usb_lease_verified: bool,
    pub granted_permissions: &'a BTreeSet<Permission>,
    pub policy_profile: &'a str,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BootProcessReceipt {
    pub step_index: usize,
    pub instruction: String,
    pub executable_sha256: String,
    pub asset_role: Option<AssetRole>,
    pub asset_sha256: Option<String>,
    pub status_code: Option<i32>,
    pub process_success: bool,
    pub cleanup_verified: bool,
    pub stdout_sha256: String,
    pub stderr_sha256: String,
    pub stdout_bytes: usize,
    pub stderr_bytes: usize,
    pub elapsed_millis: u128,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CheckpointEvidence {
    pub checkpoint: BootCheckpoint,
    pub same_device: bool,
    pub observed_mode: DeviceMode,
    pub environment_marker: String,
    pub evidence_sha256: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RamdiskBootRuntime {
    pub session_id: Uuid,
    pub pack_id: String,
    pub product_type: String,
    pub board_config: String,
    pub cpid: String,
    pub firmware_build: String,
    pub irecovery_sha256: String,
    pub next_step: usize,
    pub completed_checkpoints: BTreeSet<BootCheckpoint>,
    pub process_receipts: Vec<BootProcessReceipt>,
    pub checkpoint_hashes: BTreeMap<BootCheckpoint, String>,
    pub failed: bool,
    pub failure: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NextInstruction {
    ProcessRequired {
        step_index: usize,
        summary: String,
    },
    WaitRequired {
        step_index: usize,
        millis: u64,
    },
    CheckpointRequired {
        step_index: usize,
        checkpoint: BootCheckpoint,
    },
    Complete,
    Failed {
        reason: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RamdiskBootFinalProof {
    pub session_id: Uuid,
    pub pack_id: String,
    pub verified: bool,
    pub completed_steps: usize,
    pub process_receipt_count: usize,
    pub final_checkpoint: Option<BootCheckpoint>,
    pub blockers: Vec<String>,
}

pub fn required_permissions() -> BTreeSet<Permission> {
    BTreeSet::from([
        Permission::DeviceObserve,
        Permission::UsbRead,
        Permission::UsbWrite,
        Permission::ProcessSpawn,
        Permission::RamdiskBoot,
    ])
}

pub fn validate_irecovery_manifest(
    manifest: &IRecoveryProviderManifest,
    policy_profile: &str,
) -> Result<(), RamdiskBootError> {
    if manifest.schema_version != RAMDISK_BOOT_VERSION {
        return Err(RamdiskBootError::UnsupportedVersion(
            manifest.schema_version.clone(),
        ));
    }
    if manifest.provider_id.trim().is_empty()
        || manifest.source_repository != IRECOVERY_SOURCE_REPOSITORY
        || manifest.source_commit != IRECOVERY_SOURCE_COMMIT
        || manifest.licence != IRECOVERY_LICENCE
    {
        return Err(RamdiskBootError::InvalidIRecoveryProvenance);
    }
    if manifest.requested_permissions != required_permissions() {
        return Err(RamdiskBootError::PermissionContractMismatch);
    }
    let mandatory = [
        "irecovery_hash_verified",
        "asset_hash_verified_before_send",
        "fixed_step_order_enforced",
        "process_cleanup_verified",
        "same_device_checkpoints",
        "final_environment_verified",
    ];
    if mandatory
        .iter()
        .any(|proof| !manifest.proof_requirements.contains(*proof))
    {
        return Err(RamdiskBootError::MissingMandatoryProof);
    }
    if let Some(hash) = manifest.executable_sha256.as_deref() {
        validate_sha256(hash)?;
    }
    if policy_profile == "stable" {
        if manifest.maturity != Maturity::Stable {
            return Err(RamdiskBootError::ImmatureStableProvider);
        }
        if manifest.executable_sha256.is_none() {
            return Err(RamdiskBootError::UnpinnedIRecovery);
        }
    }
    Ok(())
}

pub fn start_runtime(
    request: BootStartRequest<'_>,
) -> Result<RamdiskBootRuntime, RamdiskBootError> {
    validate_pack(request.pack)?;
    validate_irecovery_manifest(request.irecovery_manifest, request.policy_profile)?;
    if !request.authorized_device_service || !request.explicit_operator_authorization {
        return Err(RamdiskBootError::AuthorizationRequired);
    }
    if !request.usb_lease_verified {
        return Err(RamdiskBootError::UsbLeaseRequired);
    }
    if request.granted_permissions != &required_permissions() {
        return Err(RamdiskBootError::PermissionGrantMismatch);
    }
    if !request.gaster_proof.verified
        || request.gaster_proof.observed_mode != DeviceMode::PwnedDfu
        || request.gaster_proof.pwn_provider.as_deref() != Some("checkm8")
    {
        return Err(RamdiskBootError::GasterFinalProofRequired);
    }
    let cpid = normalize_cpid(&request.pack.cpid)?;
    if request.gaster_proof.normalized_cpid != cpid
        || normalize_cpid(&request.locked_identity.cpid)? != cpid
    {
        return Err(RamdiskBootError::CpidScopeMismatch);
    }
    if request.locked_identity.product_type.as_deref() != Some(request.pack.product_type.as_str())
        || request.locked_identity.board_config.as_deref()
            != Some(request.pack.board_config.as_str())
    {
        return Err(RamdiskBootError::DeviceScopeMismatch);
    }
    if request.pack.boot_steps.first()
        != Some(&BootStep::RequireCheckpoint(
            BootCheckpoint::PwnedDfuVerified,
        ))
    {
        return Err(RamdiskBootError::MissingInitialPwnCheckpoint);
    }

    let expected_hash = request
        .irecovery_manifest
        .executable_sha256
        .clone()
        .ok_or(RamdiskBootError::UnpinnedIRecovery)?;
    let observed_hash = sha256_file(&request.installation.irecovery_executable)?;
    if observed_hash != expected_hash {
        return Err(RamdiskBootError::IRecoveryHashMismatch {
            expected: expected_hash,
            observed: observed_hash,
        });
    }
    canonical_directory(&request.installation.asset_root)?;
    canonical_directory(&request.installation.working_directory)?;

    Ok(RamdiskBootRuntime {
        session_id: request.session_id,
        pack_id: request.pack.pack_id.clone(),
        product_type: request.pack.product_type.clone(),
        board_config: request.pack.board_config.clone(),
        cpid,
        firmware_build: request.pack.firmware_build.clone(),
        irecovery_sha256: request
            .irecovery_manifest
            .executable_sha256
            .clone()
            .ok_or(RamdiskBootError::UnpinnedIRecovery)?,
        next_step: 1,
        completed_checkpoints: BTreeSet::from([BootCheckpoint::PwnedDfuVerified]),
        process_receipts: Vec::new(),
        checkpoint_hashes: BTreeMap::new(),
        failed: false,
        failure: None,
    })
}

pub fn next_instruction(
    runtime: &RamdiskBootRuntime,
    pack: &RamdiskProviderPack,
) -> NextInstruction {
    if runtime.failed {
        return NextInstruction::Failed {
            reason: runtime
                .failure
                .clone()
                .unwrap_or_else(|| "ramdisk boot runtime failed".to_owned()),
        };
    }
    let Some(step) = pack.boot_steps.get(runtime.next_step) else {
        return NextInstruction::Complete;
    };
    match step {
        BootStep::SendAsset(role) => NextInstruction::ProcessRequired {
            step_index: runtime.next_step,
            summary: format!("send_asset:{role:?}"),
        },
        BootStep::RecoveryCommand(command) => NextInstruction::ProcessRequired {
            step_index: runtime.next_step,
            summary: format!("recovery_command:{command:?}"),
        },
        BootStep::WaitMillis(millis) => NextInstruction::WaitRequired {
            step_index: runtime.next_step,
            millis: *millis,
        },
        BootStep::RequireCheckpoint(checkpoint) | BootStep::ProveCheckpoint(checkpoint) => {
            NextInstruction::CheckpointRequired {
                step_index: runtime.next_step,
                checkpoint: checkpoint.clone(),
            }
        }
    }
}

pub fn execute_current_process_step(
    process_policy: &ProcessPolicy,
    runtime: &mut RamdiskBootRuntime,
    pack: &RamdiskProviderPack,
    installation: &BootInstallation,
) -> Result<BootProcessReceipt, RamdiskBootError> {
    ensure_runtime_scope(runtime, pack)?;
    let step = pack
        .boot_steps
        .get(runtime.next_step)
        .ok_or(RamdiskBootError::NoCurrentStep)?;
    let executable_hash = sha256_file(&installation.irecovery_executable)?;
    if executable_hash != runtime.irecovery_sha256 {
        return Err(RamdiskBootError::IRecoveryHashChanged);
    }

    let (args, instruction, asset_role, asset_hash) = match step {
        BootStep::SendAsset(role) => {
            let asset = pack
                .assets
                .get(role)
                .ok_or_else(|| RamdiskBootError::MissingAsset(role.clone()))?;
            let path = resolve_asset(&installation.asset_root, &asset.relative_path)?;
            let hash = sha256_file(&path)?;
            if hash != asset.sha256 {
                return Err(RamdiskBootError::AssetHashMismatch(role.clone()));
            }
            (
                vec!["-f".to_owned(), path.to_string_lossy().into_owned()],
                format!("send_asset:{role:?}"),
                Some(role.clone()),
                Some(hash),
            )
        }
        BootStep::RecoveryCommand(command) => (
            vec!["-c".to_owned(), fixed_command(command).to_owned()],
            format!("recovery_command:{command:?}"),
            None,
            None,
        ),
        _ => return Err(RamdiskBootError::CurrentStepIsNotProcess),
    };

    let outcome = run_supervised(
        process_policy,
        &ProcessSpec {
            executable: installation.irecovery_executable.clone(),
            args,
            environment: BTreeMap::new(),
            working_directory: installation.working_directory.clone(),
        },
    )?;
    let receipt = process_receipt(
        runtime.next_step,
        instruction,
        executable_hash,
        asset_role,
        asset_hash,
        outcome,
    );
    if !receipt.process_success || !receipt.cleanup_verified {
        runtime.failed = true;
        runtime.failure = Some(format!(
            "iRecovery step {} failed or did not clean up",
            runtime.next_step
        ));
        return Err(RamdiskBootError::ProcessStepFailed(receipt));
    }
    runtime.process_receipts.push(receipt.clone());
    runtime.next_step += 1;
    Ok(receipt)
}

pub fn acknowledge_wait(
    runtime: &mut RamdiskBootRuntime,
    pack: &RamdiskProviderPack,
    elapsed_millis: u64,
) -> Result<(), RamdiskBootError> {
    ensure_runtime_scope(runtime, pack)?;
    let required = match pack.boot_steps.get(runtime.next_step) {
        Some(BootStep::WaitMillis(value)) => *value,
        _ => return Err(RamdiskBootError::CurrentStepIsNotWait),
    };
    if elapsed_millis < required {
        return Err(RamdiskBootError::WaitTooShort {
            required,
            observed: elapsed_millis,
        });
    }
    runtime.next_step += 1;
    Ok(())
}

pub fn acknowledge_checkpoint(
    runtime: &mut RamdiskBootRuntime,
    pack: &RamdiskProviderPack,
    evidence: CheckpointEvidence,
) -> Result<(), RamdiskBootError> {
    ensure_runtime_scope(runtime, pack)?;
    let expected = match pack.boot_steps.get(runtime.next_step) {
        Some(BootStep::RequireCheckpoint(value)) | Some(BootStep::ProveCheckpoint(value)) => value,
        _ => return Err(RamdiskBootError::CurrentStepIsNotCheckpoint),
    };
    if &evidence.checkpoint != expected {
        return Err(RamdiskBootError::CheckpointMismatch);
    }
    validate_sha256(&evidence.evidence_sha256)?;
    if !evidence.same_device {
        return Err(RamdiskBootError::CheckpointDeviceMismatch);
    }
    validate_checkpoint_evidence(&evidence)?;
    runtime
        .completed_checkpoints
        .insert(evidence.checkpoint.clone());
    runtime
        .checkpoint_hashes
        .insert(evidence.checkpoint, evidence.evidence_sha256);
    runtime.next_step += 1;
    Ok(())
}

pub fn finalize_runtime(
    runtime: &RamdiskBootRuntime,
    pack: &RamdiskProviderPack,
) -> RamdiskBootFinalProof {
    let mut blockers = Vec::new();
    if runtime.failed {
        blockers.push(
            runtime
                .failure
                .clone()
                .unwrap_or_else(|| "ramdisk boot runtime failed".to_owned()),
        );
    }
    if runtime.next_step != pack.boot_steps.len() {
        blockers.push("ramdisk boot plan is incomplete".to_owned());
    }
    let final_checkpoint = pack.boot_steps.iter().rev().find_map(|step| match step {
        BootStep::ProveCheckpoint(checkpoint) => Some(checkpoint.clone()),
        _ => None,
    });
    if let Some(checkpoint) = final_checkpoint.as_ref() {
        if !runtime.completed_checkpoints.contains(checkpoint) {
            blockers.push("final environment checkpoint is not proved".to_owned());
        }
    } else {
        blockers.push("pack has no final environment checkpoint".to_owned());
    }
    if runtime
        .process_receipts
        .iter()
        .any(|receipt| !receipt.process_success || !receipt.cleanup_verified)
    {
        blockers.push("one or more iRecovery process receipts are unverified".to_owned());
    }

    RamdiskBootFinalProof {
        session_id: runtime.session_id,
        pack_id: runtime.pack_id.clone(),
        verified: blockers.is_empty(),
        completed_steps: runtime.next_step.min(pack.boot_steps.len()),
        process_receipt_count: runtime.process_receipts.len(),
        final_checkpoint,
        blockers,
    }
}

fn ensure_runtime_scope(
    runtime: &RamdiskBootRuntime,
    pack: &RamdiskProviderPack,
) -> Result<(), RamdiskBootError> {
    if runtime.failed {
        return Err(RamdiskBootError::RuntimeFailed);
    }
    if runtime.pack_id != pack.pack_id
        || runtime.product_type != pack.product_type
        || runtime.board_config != pack.board_config
        || runtime.cpid != normalize_cpid(&pack.cpid)?
        || runtime.firmware_build != pack.firmware_build
    {
        return Err(RamdiskBootError::RuntimePackMismatch);
    }
    Ok(())
}

fn validate_checkpoint_evidence(evidence: &CheckpointEvidence) -> Result<(), RamdiskBootError> {
    let valid = match evidence.checkpoint {
        BootCheckpoint::PwnedDfuVerified => {
            evidence.observed_mode == DeviceMode::PwnedDfu
                && evidence.environment_marker == "PWND:[checkm8]"
        }
        BootCheckpoint::PatchedIbootReady => {
            matches!(
                evidence.observed_mode,
                DeviceMode::Recovery | DeviceMode::PwnedIbss | DeviceMode::PwnedIbec
            ) && evidence.environment_marker == "patched_iboot_ready"
        }
        BootCheckpoint::RamdiskReady => {
            evidence.observed_mode == DeviceMode::RamdiskSsh
                && evidence.environment_marker == "sshrd_ready"
        }
        BootCheckpoint::PurpleDiagnosticReady => {
            evidence.observed_mode == DeviceMode::PurpleDiagnostic
                && evidence.environment_marker == "purple_diags_ready"
        }
    };
    if valid {
        Ok(())
    } else {
        Err(RamdiskBootError::InvalidCheckpointEvidence(
            evidence.checkpoint.clone(),
        ))
    }
}

fn fixed_command(command: &FixedRecoveryCommand) -> &'static str {
    match command {
        FixedRecoveryCommand::Go => "go",
        FixedRecoveryCommand::SetPictureOne => "setpicture 0x1",
        FixedRecoveryCommand::Ramdisk => "ramdisk",
        FixedRecoveryCommand::DeviceTree => "devicetree",
        FixedRecoveryCommand::Firmware => "firmware",
        FixedRecoveryCommand::BootX => "bootx",
    }
}

fn resolve_asset(root: &Path, relative: &str) -> Result<PathBuf, RamdiskBootError> {
    let root = canonical_directory(root)?;
    let candidate = root.join(relative).canonicalize()?;
    if !candidate.is_file() || !candidate.starts_with(&root) {
        return Err(RamdiskBootError::AssetOutsideApprovedRoot(candidate));
    }
    Ok(candidate)
}

fn canonical_directory(path: &Path) -> Result<PathBuf, RamdiskBootError> {
    let canonical = path.canonicalize()?;
    if !canonical.is_dir() {
        return Err(RamdiskBootError::ExpectedDirectory(canonical));
    }
    Ok(canonical)
}

fn process_receipt(
    step_index: usize,
    instruction: String,
    executable_sha256: String,
    asset_role: Option<AssetRole>,
    asset_sha256: Option<String>,
    outcome: SupervisedOutcome,
) -> BootProcessReceipt {
    BootProcessReceipt {
        step_index,
        instruction,
        executable_sha256,
        asset_role,
        asset_sha256,
        status_code: outcome.status_code,
        process_success: outcome.success,
        cleanup_verified: outcome.cleanup.verified(),
        stdout_sha256: to_hex(&Sha256::digest(&outcome.stdout.bytes)),
        stderr_sha256: to_hex(&Sha256::digest(&outcome.stderr.bytes)),
        stdout_bytes: outcome.stdout.total_bytes,
        stderr_bytes: outcome.stderr.total_bytes,
        elapsed_millis: outcome.elapsed_millis,
    }
}

pub fn sha256_file(path: impl AsRef<Path>) -> Result<String, RamdiskBootError> {
    let mut file = File::open(path)?;
    let mut digest = Sha256::new();
    let mut buffer = [0_u8; 64 * 1024];
    loop {
        let read = file.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        digest.update(&buffer[..read]);
    }
    Ok(to_hex(&digest.finalize()))
}

fn normalize_cpid(value: &str) -> Result<String, RamdiskBootError> {
    let trimmed = value.trim();
    let digits = trimmed
        .strip_prefix("0x")
        .or_else(|| trimmed.strip_prefix("0X"))
        .unwrap_or(trimmed)
        .to_ascii_uppercase();
    if digits.len() != 4 || !digits.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(RamdiskBootError::InvalidCpid(value.to_owned()));
    }
    Ok(digits)
}

fn validate_sha256(value: &str) -> Result<(), RamdiskBootError> {
    if value.len() != 64 || !value.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(RamdiskBootError::InvalidSha256(value.to_owned()));
    }
    Ok(())
}

fn to_hex(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        output.push(HEX[(byte >> 4) as usize] as char);
        output.push(HEX[(byte & 0x0f) as usize] as char);
    }
    output
}

#[derive(Debug, thiserror::Error)]
pub enum RamdiskBootError {
    #[error("unsupported ramdisk boot version: {0}")]
    UnsupportedVersion(String),
    #[error("iRecovery provenance does not match the approved source pin")]
    InvalidIRecoveryProvenance,
    #[error("iRecovery permission contract mismatch")]
    PermissionContractMismatch,
    #[error("iRecovery provider is missing a mandatory proof")]
    MissingMandatoryProof,
    #[error("iRecovery provider is not mature enough for Stable")]
    ImmatureStableProvider,
    #[error("iRecovery executable is not hash-pinned")]
    UnpinnedIRecovery,
    #[error("device-service and explicit operator authorization are required")]
    AuthorizationRequired,
    #[error("an active USB lease is required")]
    UsbLeaseRequired,
    #[error("granted permissions do not exactly match the boot contract")]
    PermissionGrantMismatch,
    #[error("verified Gaster pwned-DFU proof is required")]
    GasterFinalProofRequired,
    #[error("CPID differs between pack, locked device, and Gaster proof")]
    CpidScopeMismatch,
    #[error("product or board differs between pack and locked device")]
    DeviceScopeMismatch,
    #[error("boot plan does not begin with pwned-DFU proof")]
    MissingInitialPwnCheckpoint,
    #[error("iRecovery executable hash mismatch: expected {expected}, observed {observed}")]
    IRecoveryHashMismatch { expected: String, observed: String },
    #[error("iRecovery executable hash changed after runtime creation")]
    IRecoveryHashChanged,
    #[error("runtime and provider pack scope differ")]
    RuntimePackMismatch,
    #[error("runtime is already failed")]
    RuntimeFailed,
    #[error("there is no current boot step")]
    NoCurrentStep,
    #[error("current boot step is not a process step")]
    CurrentStepIsNotProcess,
    #[error("current boot step is not a wait")]
    CurrentStepIsNotWait,
    #[error("current boot step is not a checkpoint")]
    CurrentStepIsNotCheckpoint,
    #[error("wait was shorter than required: required {required}, observed {observed}")]
    WaitTooShort { required: u64, observed: u64 },
    #[error("checkpoint type does not match the current boot step")]
    CheckpointMismatch,
    #[error("checkpoint belongs to a different device")]
    CheckpointDeviceMismatch,
    #[error("invalid checkpoint evidence for {0:?}")]
    InvalidCheckpointEvidence(BootCheckpoint),
    #[error("missing asset: {0:?}")]
    MissingAsset(AssetRole),
    #[error("asset path is outside the approved root: {0}")]
    AssetOutsideApprovedRoot(PathBuf),
    #[error("asset hash mismatch: {0:?}")]
    AssetHashMismatch(AssetRole),
    #[error("expected directory: {0}")]
    ExpectedDirectory(PathBuf),
    #[error("iRecovery process step failed: {0:?}")]
    ProcessStepFailed(BootProcessReceipt),
    #[error("invalid CPID: {0}")]
    InvalidCpid(String),
    #[error("invalid SHA-256: {0}")]
    InvalidSha256(String),
    #[error(transparent)]
    Pack(#[from] tg_ramdisk_pack::RamdiskPackError),
    #[error(transparent)]
    Process(#[from] tg_process::ProcessError),
    #[error(transparent)]
    Io(#[from] std::io::Error),
}
